# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Nust SE-12\3rd Semester\DataBase\project\UI\clientForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(761, 571)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(30, 20, 711, 521))
        self.tabWidget.setStyleSheet("*{\n"
"     font-family: \"Segoe UI\";\n"
"\n"
"}\n"
"QLabel{\n"
"color: white\n"
"\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("QLineEdit{\n"
"background: rgb(197, 197, 197);\n"
"border-radius:5px;\n"
"font: 11pt \"Segoe UI\";\n"
"}\n"
"QLabel {\n"
"color: black;\n"
"\n"
"}")
        self.tab.setObjectName("tab")
        self.c_first_name = QtWidgets.QLabel(self.tab)
        self.c_first_name.setGeometry(QtCore.QRect(30, 90, 91, 21))
        self.c_first_name.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"")
        self.c_first_name.setObjectName("c_first_name")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(150, 90, 171, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(490, 90, 171, 31))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.c_last_name = QtWidgets.QLabel(self.tab)
        self.c_last_name.setGeometry(QtCore.QRect(390, 90, 101, 21))
        self.c_last_name.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"")
        self.c_last_name.setObjectName("c_last_name")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(150, 140, 171, 31))
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.c_cnic = QtWidgets.QLabel(self.tab)
        self.c_cnic.setGeometry(QtCore.QRect(20, 140, 121, 31))
        self.c_cnic.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;")
        self.c_cnic.setObjectName("c_cnic")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setGeometry(QtCore.QRect(490, 140, 171, 31))
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.c_father_name = QtWidgets.QLabel(self.tab)
        self.c_father_name.setGeometry(QtCore.QRect(360, 140, 121, 21))
        self.c_father_name.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"")
        self.c_father_name.setObjectName("c_father_name")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_5.setGeometry(QtCore.QRect(150, 190, 171, 31))
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.c_dob = QtWidgets.QLabel(self.tab)
        self.c_dob.setGeometry(QtCore.QRect(30, 190, 101, 21))
        self.c_dob.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"")
        self.c_dob.setObjectName("c_dob")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_6.setGeometry(QtCore.QRect(490, 190, 171, 31))
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.c_gender = QtWidgets.QLabel(self.tab)
        self.c_gender.setGeometry(QtCore.QRect(410, 190, 71, 21))
        self.c_gender.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"")
        self.c_gender.setObjectName("c_gender")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_7.setGeometry(QtCore.QRect(150, 240, 171, 31))
        self.lineEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.c_phone = QtWidgets.QLabel(self.tab)
        self.c_phone.setGeometry(QtCore.QRect(30, 240, 91, 21))
        self.c_phone.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"")
        self.c_phone.setObjectName("c_phone")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_8.setGeometry(QtCore.QRect(490, 240, 171, 31))
        self.lineEdit_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.c_mobile = QtWidgets.QLabel(self.tab)
        self.c_mobile.setGeometry(QtCore.QRect(390, 230, 91, 21))
        self.c_mobile.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"")
        self.c_mobile.setObjectName("c_mobile")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_9.setGeometry(QtCore.QRect(150, 290, 171, 31))
        self.lineEdit_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(30, 290, 111, 21))
        self.label_11.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"")
        self.label_11.setObjectName("label_11")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_10.setGeometry(QtCore.QRect(490, 290, 171, 31))
        self.lineEdit_10.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(410, 290, 81, 21))
        self.label_12.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"")
        self.label_12.setObjectName("label_12")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_12.setGeometry(QtCore.QRect(490, 340, 171, 31))
        self.lineEdit_12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(350, 340, 141, 21))
        self.label_14.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"")
        self.label_14.setObjectName("label_14")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(30, 340, 101, 21))
        self.label_13.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"")
        self.label_13.setObjectName("label_13")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_11.setGeometry(QtCore.QRect(150, 340, 171, 31))
        self.lineEdit_11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(240, 10, 261, 31))
        self.label_3.setStyleSheet("font: 700 9pt \"Segoe UI\";\n"
"font-size: 23px;\n"
"color: white")
        self.label_3.setObjectName("label_3")
        self.Next1 = QtWidgets.QPushButton(self.tab)
        self.Next1.setGeometry(QtCore.QRect(600, 450, 83, 29))
        self.Next1.setStyleSheet("background-color: rgb(52, 156, 161);\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 13px;\n"
"color: black;\n"
"")
        self.Next1.setObjectName("Next1")
        self.Home1 = QtWidgets.QPushButton(self.tab)
        self.Home1.setGeometry(QtCore.QRect(10, 10, 71, 29))
        self.Home1.setStyleSheet("background-color: rgb(52, 156, 161);\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 13px;\n"
"color: black;")
        self.Home1.setObjectName("Home1")
        self.label_36 = QtWidgets.QLabel(self.tab)
        self.label_36.setGeometry(QtCore.QRect(-10, 0, 721, 501))
        self.label_36.setStyleSheet("QLabel{\n"
"color: white\n"
"\n"
"}")
        self.label_36.setText("")
        self.label_36.setPixmap(QtGui.QPixmap("e:\\Nust SE-12\\3rd Semester\\DataBase\\project\\UI\\../assets/background-2.jpg"))
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName("label_36")
        self.label_36.raise_()
        self.c_first_name.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.c_last_name.raise_()
        self.lineEdit_3.raise_()
        self.c_cnic.raise_()
        self.lineEdit_4.raise_()
        self.c_father_name.raise_()
        self.lineEdit_5.raise_()
        self.c_dob.raise_()
        self.lineEdit_6.raise_()
        self.c_gender.raise_()
        self.lineEdit_7.raise_()
        self.c_phone.raise_()
        self.lineEdit_8.raise_()
        self.c_mobile.raise_()
        self.lineEdit_9.raise_()
        self.label_11.raise_()
        self.lineEdit_10.raise_()
        self.label_12.raise_()
        self.lineEdit_12.raise_()
        self.label_14.raise_()
        self.label_13.raise_()
        self.lineEdit_11.raise_()
        self.label_3.raise_()
        self.Next1.raise_()
        self.Home1.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("QLineEdit{\n"
"background: rgb(197, 197, 197);\n"
"border-radius:5px;\n"
"font: 11pt \"Segoe UI\";\n"
"}\n"
"QLabel {\n"
"color: black;\n"
"\n"
"}")
        self.tab_2.setObjectName("tab_2")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(260, 20, 271, 31))
        self.label_17.setStyleSheet("color: white;\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 23px")
        self.label_17.setObjectName("label_17")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_16.setGeometry(QtCore.QRect(470, 110, 171, 31))
        self.lineEdit_16.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black\n"
"")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(370, 110, 101, 21))
        self.label_19.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"")
        self.label_19.setObjectName("label_19")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_17.setGeometry(QtCore.QRect(160, 170, 171, 31))
        self.lineEdit_17.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(100, 180, 51, 21))
        self.label_20.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"")
        self.label_20.setObjectName("label_20")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_18.setGeometry(QtCore.QRect(470, 170, 171, 31))
        self.lineEdit_18.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(370, 170, 81, 21))
        self.label_21.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"")
        self.label_21.setObjectName("label_21")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_19.setGeometry(QtCore.QRect(160, 230, 171, 31))
        self.lineEdit_19.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(100, 230, 61, 21))
        self.label_22.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"")
        self.label_22.setObjectName("label_22")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_20.setGeometry(QtCore.QRect(470, 230, 171, 31))
        self.lineEdit_20.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black\n"
"")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(370, 240, 61, 21))
        self.label_23.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"")
        self.label_23.setObjectName("label_23")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_21.setGeometry(QtCore.QRect(160, 290, 171, 31))
        self.lineEdit_21.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(80, 290, 81, 21))
        self.label_24.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"")
        self.label_24.setObjectName("label_24")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_22.setGeometry(QtCore.QRect(470, 290, 171, 31))
        self.lineEdit_22.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(370, 290, 91, 31))
        self.label_25.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"")
        self.label_25.setObjectName("label_25")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_23.setGeometry(QtCore.QRect(160, 110, 171, 31))
        self.lineEdit_23.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_23.setText("")
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(60, 110, 91, 21))
        self.label_26.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"")
        self.label_26.setObjectName("label_26")
        self.Next2 = QtWidgets.QPushButton(self.tab_2)
        self.Next2.setGeometry(QtCore.QRect(610, 450, 83, 29))
        self.Next2.setStyleSheet("background-color: rgb(52, 156, 161);\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 13px;\n"
"color: black;")
        self.Next2.setObjectName("Next2")
        self.Prev1 = QtWidgets.QPushButton(self.tab_2)
        self.Prev1.setGeometry(QtCore.QRect(10, 450, 83, 29))
        self.Prev1.setStyleSheet("background-color: rgb(52, 156, 161);\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 13px;\n"
"color: black;")
        self.Prev1.setObjectName("Prev1")
        self.Home2 = QtWidgets.QPushButton(self.tab_2)
        self.Home2.setGeometry(QtCore.QRect(10, 10, 71, 29))
        self.Home2.setStyleSheet("background-color: rgb(52, 156, 161);\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 13px;\n"
"color: black;")
        self.Home2.setObjectName("Home2")
        self.label_37 = QtWidgets.QLabel(self.tab_2)
        self.label_37.setGeometry(QtCore.QRect(0, -10, 711, 501))
        self.label_37.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.label_37.setText("")
        self.label_37.setPixmap(QtGui.QPixmap("e:\\Nust SE-12\\3rd Semester\\DataBase\\project\\UI\\../assets/background-2.jpg"))
        self.label_37.setScaledContents(True)
        self.label_37.setObjectName("label_37")
        self.label_37.raise_()
        self.label_17.raise_()
        self.lineEdit_16.raise_()
        self.label_19.raise_()
        self.lineEdit_17.raise_()
        self.label_20.raise_()
        self.lineEdit_18.raise_()
        self.label_21.raise_()
        self.lineEdit_19.raise_()
        self.label_22.raise_()
        self.lineEdit_20.raise_()
        self.label_23.raise_()
        self.lineEdit_21.raise_()
        self.label_24.raise_()
        self.lineEdit_22.raise_()
        self.label_25.raise_()
        self.lineEdit_23.raise_()
        self.label_26.raise_()
        self.Next2.raise_()
        self.Prev1.raise_()
        self.Home2.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setStyleSheet("QLineEdit{\n"
"background: rgb(197, 197, 197);\n"
"border-radius:5px;\n"
"font: 11pt \"Segoe UI\";\n"
"}\n"
"")
        self.tab_3.setObjectName("tab_3")
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(260, 20, 231, 31))
        self.label_18.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 23px")
        self.label_18.setObjectName("label_18")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_25.setGeometry(QtCore.QRect(200, 140, 161, 31))
        self.lineEdit_25.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_25.setText("")
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.label_28 = QtWidgets.QLabel(self.tab_3)
        self.label_28.setGeometry(QtCore.QRect(40, 140, 121, 21))
        self.label_28.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"color: black;")
        self.label_28.setObjectName("label_28")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_27.setGeometry(QtCore.QRect(500, 140, 161, 31))
        self.lineEdit_27.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_27.setText("")
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.label_30 = QtWidgets.QLabel(self.tab_3)
        self.label_30.setGeometry(QtCore.QRect(380, 140, 111, 21))
        self.label_30.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"color: black;")
        self.label_30.setObjectName("label_30")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_28.setGeometry(QtCore.QRect(500, 190, 161, 31))
        self.lineEdit_28.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.label_31 = QtWidgets.QLabel(self.tab_3)
        self.label_31.setGeometry(QtCore.QRect(410, 190, 81, 21))
        self.label_31.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"color: black;")
        self.label_31.setObjectName("label_31")
        self.label_34 = QtWidgets.QLabel(self.tab_3)
        self.label_34.setGeometry(QtCore.QRect(40, 190, 131, 21))
        self.label_34.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"color: black;")
        self.label_34.setObjectName("label_34")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_31.setGeometry(QtCore.QRect(200, 190, 161, 31))
        self.lineEdit_31.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.label_33 = QtWidgets.QLabel(self.tab_3)
        self.label_33.setGeometry(QtCore.QRect(40, 240, 161, 21))
        self.label_33.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"color: black;")
        self.label_33.setObjectName("label_33")
        self.Prev2 = QtWidgets.QPushButton(self.tab_3)
        self.Prev2.setGeometry(QtCore.QRect(10, 450, 83, 29))
        self.Prev2.setStyleSheet("background-color: rgb(52, 156, 161);\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 13px;\n"
"color: black;")
        self.Prev2.setObjectName("Prev2")
        self.Next3 = QtWidgets.QPushButton(self.tab_3)
        self.Next3.setGeometry(QtCore.QRect(610, 450, 83, 29))
        self.Next3.setStyleSheet("background-color: rgb(52, 156, 161);\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 13px;\n"
"color: black;")
        self.Next3.setObjectName("Next3")
        self.Home3 = QtWidgets.QPushButton(self.tab_3)
        self.Home3.setGeometry(QtCore.QRect(10, 10, 71, 29))
        self.Home3.setStyleSheet("background-color: rgb(52, 156, 161);\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 13px;\n"
"color: black;")
        self.Home3.setObjectName("Home3")
        self.comboBox = QtWidgets.QComboBox(self.tab_3)
        self.comboBox.setGeometry(QtCore.QRect(200, 240, 51, 21))
        self.comboBox.setStyleSheet("font: 700 10pt \"Segoe UI\";\n"
"color: black;\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_38 = QtWidgets.QLabel(self.tab_3)
        self.label_38.setGeometry(QtCore.QRect(0, 0, 711, 501))
        self.label_38.setText("")
        self.label_38.setPixmap(QtGui.QPixmap("e:\\Nust SE-12\\3rd Semester\\DataBase\\project\\UI\\../assets/background-2.jpg"))
        self.label_38.setScaledContents(True)
        self.label_38.setObjectName("label_38")
        self.label_38.raise_()
        self.label_18.raise_()
        self.lineEdit_25.raise_()
        self.label_28.raise_()
        self.lineEdit_27.raise_()
        self.label_30.raise_()
        self.lineEdit_28.raise_()
        self.label_31.raise_()
        self.label_34.raise_()
        self.lineEdit_31.raise_()
        self.label_33.raise_()
        self.Prev2.raise_()
        self.Next3.raise_()
        self.Home3.raise_()
        self.comboBox.raise_()
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setStyleSheet("QLineEdit{\n"
"background: rgb(197, 197, 197);\n"
"border-radius:5px;\n"
"font: 11pt \"Segoe UI\";\n"
"}")
        self.tab_4.setObjectName("tab_4")
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(250, 20, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 23px")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(220, 130, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"color: black;")
        self.label_2.setObjectName("label_2")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_15.setGeometry(QtCore.QRect(350, 130, 161, 28))
        self.lineEdit_15.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(180, 190, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"color: black;")
        self.label_5.setObjectName("label_5")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_33.setGeometry(QtCore.QRect(350, 190, 161, 28))
        self.lineEdit_33.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.saveButton = QtWidgets.QPushButton(self.tab_4)
        self.saveButton.setGeometry(QtCore.QRect(610, 440, 83, 29))
        self.saveButton.setStyleSheet("background-color: rgb(52, 156, 161);\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 13px;\n"
"color: black;")
        self.saveButton.setObjectName("saveButton")
        self.Home4 = QtWidgets.QPushButton(self.tab_4)
        self.Home4.setGeometry(QtCore.QRect(10, 10, 71, 29))
        self.Home4.setStyleSheet("background-color: rgb(52, 156, 161);\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 13px;\n"
"color: black;")
        self.Home4.setObjectName("Home4")
        self.Prev3 = QtWidgets.QPushButton(self.tab_4)
        self.Prev3.setGeometry(QtCore.QRect(20, 440, 83, 29))
        self.Prev3.setStyleSheet("background-color: rgb(52, 156, 161);\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 13px;\n"
"color: black;")
        self.Prev3.setObjectName("Prev3")
        self.label_59 = QtWidgets.QLabel(self.tab_4)
        self.label_59.setGeometry(QtCore.QRect(180, 250, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.label_59.setFont(font)
        self.label_59.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"color: black;")
        self.label_59.setObjectName("label_59")
        self.lineEdit_67 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_67.setGeometry(QtCore.QRect(350, 250, 161, 28))
        self.lineEdit_67.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 11pt \"Segoe UI\";\n"
"color: black")
        self.lineEdit_67.setObjectName("lineEdit_67")
        self.label_39 = QtWidgets.QLabel(self.tab_4)
        self.label_39.setGeometry(QtCore.QRect(0, 0, 711, 501))
        self.label_39.setText("")
        self.label_39.setPixmap(QtGui.QPixmap("e:\\Nust SE-12\\3rd Semester\\DataBase\\project\\UI\\../assets/background-2.jpg"))
        self.label_39.setScaledContents(True)
        self.label_39.setObjectName("label_39")
        self.label_39.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.lineEdit_15.raise_()
        self.label_5.raise_()
        self.lineEdit_33.raise_()
        self.saveButton.raise_()
        self.Home4.raise_()
        self.Prev3.raise_()
        self.label_59.raise_()
        self.lineEdit_67.raise_()
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(250, 20, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 23px")
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.tab_5)
        self.label_8.setGeometry(QtCore.QRect(170, 110, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"color: black;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_5)
        self.label_9.setGeometry(QtCore.QRect(170, 260, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"color: black;")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_5)
        self.label_10.setGeometry(QtCore.QRect(170, 160, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"color: black;")
        self.label_10.setObjectName("label_10")
        self.label_15 = QtWidgets.QLabel(self.tab_5)
        self.label_15.setGeometry(QtCore.QRect(170, 210, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 16px;\n"
"color: black;")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        self.label_16.setGeometry(QtCore.QRect(400, 110, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("font: 700 11pt \"Segoe UI\";\n"
"color: black;")
        self.label_16.setObjectName("label_16")
        self.label_27 = QtWidgets.QLabel(self.tab_5)
        self.label_27.setGeometry(QtCore.QRect(400, 160, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("font: 700 11pt \"Segoe UI\";\n"
"color: black;")
        self.label_27.setObjectName("label_27")
        self.label_29 = QtWidgets.QLabel(self.tab_5)
        self.label_29.setGeometry(QtCore.QRect(400, 210, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("font: 700 11pt \"Segoe UI\";\n"
"color: black;")
        self.label_29.setObjectName("label_29")
        self.label_32 = QtWidgets.QLabel(self.tab_5)
        self.label_32.setGeometry(QtCore.QRect(400, 260, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("font: 700 11pt \"Segoe UI\";\n"
"color: black;")
        self.label_32.setObjectName("label_32")
        self.Home5 = QtWidgets.QPushButton(self.tab_5)
        self.Home5.setGeometry(QtCore.QRect(10, 10, 71, 29))
        self.Home5.setStyleSheet("background-color: rgb(52, 156, 161);\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 13px;\n"
"color: black;")
        self.Home5.setObjectName("Home5")
        self.Done = QtWidgets.QPushButton(self.tab_5)
        self.Done.setGeometry(QtCore.QRect(600, 440, 83, 29))
        self.Done.setStyleSheet("background-color: rgb(52, 156, 161);\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 13px;\n"
"color: black;")
        self.Done.setObjectName("Done")
        self.label_40 = QtWidgets.QLabel(self.tab_5)
        self.label_40.setGeometry(QtCore.QRect(0, 0, 711, 501))
        self.label_40.setText("")
        self.label_40.setPixmap(QtGui.QPixmap("e:\\Nust SE-12\\3rd Semester\\DataBase\\project\\UI\\../assets/background-2.jpg"))
        self.label_40.setScaledContents(True)
        self.label_40.setObjectName("label_40")
        self.label_40.raise_()
        self.label_4.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_27.raise_()
        self.label_29.raise_()
        self.label_32.raise_()
        self.Home5.raise_()
        self.Done.raise_()
        self.tabWidget.addTab(self.tab_5, "")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(830, 700, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(810, 700, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_35 = QtWidgets.QLabel(Form)
        self.label_35.setGeometry(QtCore.QRect(0, 0, 761, 571))
        self.label_35.setText("")
        self.label_35.setPixmap(QtGui.QPixmap("e:\\Nust SE-12\\3rd Semester\\DataBase\\project\\UI\\../assets/background-1.jpg"))
        self.label_35.setScaledContents(True)
        self.label_35.setObjectName("label_35")
        self.label_35.raise_()
        self.tabWidget.raise_()
        self.label_6.raise_()
        self.label_7.raise_()

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.c_first_name.setText(_translate("Form", "First Name:"))
        self.c_last_name.setText(_translate("Form", "Last Name:"))
        self.c_cnic.setText(_translate("Form", "CNIC Number:"))
        self.c_father_name.setText(_translate("Form", "Father\'s Name:"))
        self.c_dob.setText(_translate("Form", "Date of Birth:"))
        self.c_gender.setText(_translate("Form", "Gender:"))
        self.c_phone.setText(_translate("Form", "Phone No:"))
        self.c_mobile.setText(_translate("Form", "Mobile No:"))
        self.label_11.setText(_translate("Form", "Martial Status:"))
        self.label_12.setText(_translate("Form", "Address:"))
        self.label_14.setText(_translate("Form", "Monthly Income:"))
        self.label_13.setText(_translate("Form", "Work Place:"))
        self.label_3.setText(_translate("Form", "Customer Information"))
        self.Next1.setText(_translate("Form", "Next"))
        self.Home1.setText(_translate("Form", "Home"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Tab 1"))
        self.label_17.setText(_translate("Form", "Gaurantor Information"))
        self.label_19.setText(_translate("Form", "Last Name:"))
        self.label_20.setText(_translate("Form", "CNIC:"))
        self.label_21.setText(_translate("Form", "Address:"))
        self.label_22.setText(_translate("Form", "Phone:"))
        self.label_23.setText(_translate("Form", "Mobile:"))
        self.label_24.setText(_translate("Form", "Relation:"))
        self.label_25.setText(_translate("Form", "Work Place:"))
        self.label_26.setText(_translate("Form", "First Name:"))
        self.Next2.setText(_translate("Form", "Next"))
        self.Prev1.setText(_translate("Form", "Prev"))
        self.Home2.setText(_translate("Form", "Home"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))
        self.label_18.setText(_translate("Form", "Product Information"))
        self.label_28.setText(_translate("Form", "Product Name:"))
        self.label_30.setText(_translate("Form", " Net Amount:"))
        self.label_31.setText(_translate("Form", "Advance:"))
        self.label_34.setText(_translate("Form", "Purchased Date:"))
        self.label_33.setText(_translate("Form", "Number Of Months:"))
        self.Prev2.setText(_translate("Form", "Prev"))
        self.Next3.setText(_translate("Form", "Next"))
        self.Home3.setText(_translate("Form", "Home"))
        self.comboBox.setItemText(0, _translate("Form", "3"))
        self.comboBox.setItemText(1, _translate("Form", "6"))
        self.comboBox.setItemText(2, _translate("Form", "9"))
        self.comboBox.setItemText(3, _translate("Form", "12"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Page"))
        self.label.setText(_translate("Form", "Account Information"))
        self.label_2.setText(_translate("Form", "Collector ID:"))
        self.label_5.setText(_translate("Form", "Expected End Date:"))
        self.saveButton.setText(_translate("Form", "Save"))
        self.Home4.setText(_translate("Form", "Home"))
        self.Prev3.setText(_translate("Form", "Prev"))
        self.label_59.setText(_translate("Form", "Installement Date:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Page"))
        self.label_4.setText(_translate("Form", "Account Information"))
        self.label_8.setText(_translate("Form", "Account No :"))
        self.label_9.setText(_translate("Form", "Monthly Installlement Date :"))
        self.label_10.setText(_translate("Form", "Customer Name :"))
        self.label_15.setText(_translate("Form", "Monthly Installement:"))
        self.label_16.setText(_translate("Form", "0"))
        self.label_27.setText(_translate("Form", "0"))
        self.label_29.setText(_translate("Form", "0"))
        self.label_32.setText(_translate("Form", "0"))
        self.Home5.setText(_translate("Form", "Home"))
        self.Done.setText(_translate("Form", "Done"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "Page"))
        self.label_6.setText(_translate("Form", "Collector ID"))
        self.label_7.setText(_translate("Form", "Collector ID"))
