# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Nust SE-12\3rd Semester\DataBase\project\UI\managerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(761, 571)
        Form.setStyleSheet("background-color: rgb(15, 79, 82);\n"
"")
        self.add_employee_btn = QtWidgets.QPushButton(Form)
        self.add_employee_btn.setGeometry(QtCore.QRect(320, 230, 141, 41))
        self.add_employee_btn.setStyleSheet("font: 700 9pt \"Arial\";\n"
"font-size: 12px;\n"
"color: white")
        self.add_employee_btn.setObjectName("add_employee_btn")
        self.view_employee_btn = QtWidgets.QPushButton(Form)
        self.view_employee_btn.setGeometry(QtCore.QRect(230, 360, 131, 41))
        self.view_employee_btn.setStyleSheet("font: 700 9pt \"Arial\";\n"
"font-size: 12px;\n"
"color: white")
        self.view_employee_btn.setObjectName("view_employee_btn")
        self.view_customer_btn = QtWidgets.QPushButton(Form)
        self.view_customer_btn.setGeometry(QtCore.QRect(230, 440, 131, 41))
        self.view_customer_btn.setStyleSheet("font: 700 9pt \"Arial\";\n"
"font-size: 12px;\n"
"color: white")
        self.view_customer_btn.setObjectName("view_customer_btn")
        self.view_record_btn = QtWidgets.QPushButton(Form)
        self.view_record_btn.setGeometry(QtCore.QRect(410, 360, 131, 41))
        self.view_record_btn.setStyleSheet("font: 700 9pt \"Arial\";\n"
"font-size: 12px;\n"
"color: white")
        self.view_record_btn.setObjectName("view_record_btn")
        self.view_product_btn = QtWidgets.QPushButton(Form)
        self.view_product_btn.setGeometry(QtCore.QRect(410, 440, 131, 41))
        self.view_product_btn.setStyleSheet("font: 700 9pt \"Arial\";\n"
"font-size: 12px;\n"
"color: white")
        self.view_product_btn.setObjectName("view_product_btn")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(260, 50, 431, 51))
        self.label.setStyleSheet("font-size: 50px;\n"
"color: White;\n"
"background-color: transparent;\n"
"")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(-30, -20, 811, 591))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("e:\\Nust SE-12\\3rd Semester\\DataBase\\project\\UI\\../assets/background-1.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(120, 20, 121, 111))
        self.label_2.setStyleSheet("background-color: transparent;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("e:\\Nust SE-12\\3rd Semester\\DataBase\\project\\UI\\../assets/IMS_logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(230, 170, 301, 31))
        self.label_4.setStyleSheet("font: 9pt \"Arial\";\n"
"font-size: 16px;\n"
"background-color: transparent;\n"
"color: white\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(240, 310, 221, 21))
        self.label_5.setStyleSheet("font: 9pt \"Arial\";\n"
"font-size: 16px;\n"
"color: white;\n"
"background-color: transparent;\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(180, 290, 51, 51))
        self.label_6.setStyleSheet("background-color: transparent;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("e:\\Nust SE-12\\3rd Semester\\DataBase\\project\\UI\\../assets/view.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(170, 160, 51, 51))
        self.label_7.setStyleSheet("background-color: transparent;")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("e:\\Nust SE-12\\3rd Semester\\DataBase\\project\\UI\\../assets/Add_Employees.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.signOut_btn = QtWidgets.QPushButton(Form)
        self.signOut_btn.setGeometry(QtCore.QRect(640, 10, 71, 31))
        self.signOut_btn.setStyleSheet("font: 700 9pt \"Arial\";\n"
"font-size: 12px;\n"
"color: white")
        self.signOut_btn.setObjectName("signOut_btn")
        self.label_3.raise_()
        self.add_employee_btn.raise_()
        self.view_employee_btn.raise_()
        self.view_customer_btn.raise_()
        self.view_record_btn.raise_()
        self.view_product_btn.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.signOut_btn.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.add_employee_btn.setText(_translate("Form", "Add New Employee"))
        self.view_employee_btn.setText(_translate("Form", "View Employee"))
        self.view_customer_btn.setText(_translate("Form", "View Acounts"))
        self.view_record_btn.setText(_translate("Form", "View Record"))
        self.view_product_btn.setText(_translate("Form", "View Product"))
        self.label.setText(_translate("Form", " Welcome Yameen!"))
        self.label_4.setText(_translate("Form", "Do you want to add a new employee?"))
        self.label_5.setText(_translate("Form", "What do you want to view?"))
        self.signOut_btn.setText(_translate("Form", "Sign Out"))
