# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Nust SE-12\3rd Semester\DataBase\project\UI\Records.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(726, 608)
        Form.setStyleSheet("QLable{\n"
"    color: white;\n"
"    font-size: 15px\n"
"}")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 10, 721, 601))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("e:\\Nust SE-12\\3rd Semester\\DataBase\\project\\UI\\../assets/background-2.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(260, 30, 181, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: black;\n"
"font: 700 16pt \"Segoe UI\";")
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(400, 180, 63, 20))
        self.label_4.setStyleSheet("color: black;\n"
"font: 700 14pt \"Segoe UI\";")
        self.label_4.setObjectName("label_4")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(400, 240, 31, 21))
        self.label_11.setStyleSheet("color: black;\n"
"font: 700 14pt \"Segoe UI\";")
        self.label_11.setObjectName("label_11")
        self.prev_btn = QtWidgets.QPushButton(Form)
        self.prev_btn.setGeometry(QtCore.QRect(30, 30, 61, 31))
        self.prev_btn.setStyleSheet("background-color: rgb(52, 156, 161);\n"
"font: 700 9pt \"Segoe UI\";\n"
"font-size: 13px;\n"
"color: black;")
        self.prev_btn.setObjectName("prev_btn")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(150, 270, 231, 20))
        self.label_24.setStyleSheet("color: black;\n"
"font: 700 14pt \"Segoe UI\";")
        self.label_24.setObjectName("label_24")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(240, 300, 141, 21))
        self.label_3.setStyleSheet("color: black;\n"
"font: 700 14pt \"Segoe UI\";")
        self.label_3.setObjectName("label_3")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(550, 40, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: black;\n"
"font: 14pt \"Segoe UI\";")
        self.label_25.setObjectName("label_25")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(200, 240, 181, 21))
        self.label_10.setStyleSheet("color: black;\n"
"font: 700 14pt \"Segoe UI\";")
        self.label_10.setObjectName("label_10")
        self.comboBox_3 = QtWidgets.QComboBox(Form)
        self.comboBox_3.setGeometry(QtCore.QRect(620, 40, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("background-color: rgb(52, 156, 161);\n"
"font: 9pt \"Segoe UI\";\n"
"font-size: 13px;\n"
"color: black;")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(400, 210, 31, 21))
        self.label_8.setStyleSheet("color: black;\n"
"font: 700 14pt \"Segoe UI\";")
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(650, 70, 41, 21))
        self.pushButton.setStyleSheet("background-color: rgb(52, 156, 161);\n"
"font: 9pt \"Segoe UI\";\n"
"font-size: 13px;\n"
"color: black;")
        self.pushButton.setObjectName("pushButton")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(400, 270, 41, 21))
        self.label_23.setStyleSheet("color: black;\n"
"font: 700 14pt \"Segoe UI\";")
        self.label_23.setObjectName("label_23")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(1100, 250, 141, 28))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(400, 300, 63, 20))
        self.label_6.setStyleSheet("color: black;\n"
"font: 700 14pt \"Segoe UI\";")
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(210, 210, 171, 21))
        self.label_9.setStyleSheet("color: black;\n"
"font: 700 14pt \"Segoe UI\";")
        self.label_9.setObjectName("label_9")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(180, 180, 201, 21))
        self.label_2.setStyleSheet("color: black;\n"
"font: 700 14pt \"Segoe UI\";")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_7.setText(_translate("Form", "Monthly report!"))
        self.label_4.setText(_translate("Form", "100"))
        self.label_11.setText(_translate("Form", "26"))
        self.prev_btn.setText(_translate("Form", "Home"))
        self.label_24.setText(_translate("Form", "Account to be recovered:"))
        self.label_3.setText(_translate("Form", "Product Selled:"))
        self.label_25.setText(_translate("Form", "Month"))
        self.label_10.setText(_translate("Form", "Account recovered:"))
        self.comboBox_3.setItemText(0, _translate("Form", "Current"))
        self.comboBox_3.setItemText(1, _translate("Form", "Jan"))
        self.comboBox_3.setItemText(2, _translate("Form", "Feb"))
        self.comboBox_3.setItemText(3, _translate("Form", "Mar"))
        self.comboBox_3.setItemText(4, _translate("Form", "Apr"))
        self.comboBox_3.setItemText(5, _translate("Form", "May"))
        self.comboBox_3.setItemText(6, _translate("Form", "Jun"))
        self.comboBox_3.setItemText(7, _translate("Form", "Jul"))
        self.comboBox_3.setItemText(8, _translate("Form", "Aug"))
        self.comboBox_3.setItemText(9, _translate("Form", "Sep"))
        self.comboBox_3.setItemText(10, _translate("Form", "Oct"))
        self.comboBox_3.setItemText(11, _translate("Form", "Nov"))
        self.comboBox_3.setItemText(12, _translate("Form", "Dec"))
        self.label_8.setText(_translate("Form", "26"))
        self.pushButton.setText(_translate("Form", "Apply"))
        self.label_23.setText(_translate("Form", "26"))
        self.comboBox.setItemText(0, _translate("Form", "Active Accounts"))
        self.comboBox.setItemText(1, _translate("Form", "Accounts Cleared"))
        self.comboBox.setItemText(2, _translate("Form", "All Acounts"))
        self.label_6.setText(_translate("Form", "26"))
        self.label_9.setText(_translate("Form", "Cleared Accounts:"))
        self.label_2.setText(_translate("Form", "New acounts created:"))
